<?php
/**
 * Magenizr SuezCanal
 *
 * @category  Magenizr
 * @copyright Copyright (c) 2021 - 2022 Magenizr (https://www.magenizr.com)
 * @license   https://www.magenizr.com/license Magenizr EULA
 */
?>

<?php if ($block->getHelper()->isEnabled()): ?>

    <?php $class = $block->getClass() ?>

    <div id="magenizr-suezcanal">
        <div class="content alert alert-<?= (!empty($class)) ? $block->escapeHtml($class) : ''; ?>">
            <?= $block->filterOutputHtml($block->getContent()); ?>
        </div>
    </div>

<?php endif; ?>

